# -*- coding: utf-8 -*-
"""Algoritmo de Auditoria de Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emoflr-ktI3fkllsop9MQQTDFFuSij1C
"""

LIMITE_SEGURANCA = 10000.00
def analisar_vendas():
  global LIMITE_SEGURANCA
  print("--- INICIANDO AUDITORIA DE VENDAS ---")
  try:
    # 2 Entrada de Dados com conversão protegida
    venda1 = float(input("Digite o valor da venda 1: R$ "))
    venda2 = float(input("Digite o valor da venda 2: R$ "))
    venda3 = float(input("Digite o valor da venda 3: R$ "))
    media = (venda1 + venda2 + venda3) / 3

    print(f"\nMédia calculada: R$ {media:.2f}")

    if media > LIMITE_SEGURANCA:
      print(" SISTEMA EM QUARENTENA")
      confirmacao = input("As vendas são legítimas? Alterar o limite? (s/n): ").strip().lower()
      if confirmacao == 's':
        LIMITE_SEGURANCA = float(input("Digite o novo valor do limite: R$ "))
        print(f" Limite atualizado para: R$ {LIMITE_SEGURANCA:.2f}")
    else:
      print(" Vendas validadas com sucesso.")
  except ValueError:
    print(" Erro: Por favor, insira apenas números válidos (use ponto para decimais).")

if __name__ == "__main__":
  analisar_vendas()